# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dupfind.ui'
#
# Created: Thu Dec 31 05:24:34 2009
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dupfind(object):
    def setupUi(self, dupfind):
        dupfind.setObjectName("dupfind")
        dupfind.resize(746, 421)
        self.centralwidget = QtGui.QWidget(dupfind)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_settings = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_settings.sizePolicy().hasHeightForWidth())
        self.groupBox_settings.setSizePolicy(sizePolicy)
        self.groupBox_settings.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_settings.setMaximumSize(QtCore.QSize(16777215, 81))
        self.groupBox_settings.setSizeIncrement(QtCore.QSize(1, 1))
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_settings)
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_pick_Dir = QtGui.QLabel(self.groupBox_settings)
        self.label_pick_Dir.setObjectName("label_pick_Dir")
        self.horizontalLayout.addWidget(self.label_pick_Dir)
        self.lineEdit_dir = QtGui.QLineEdit(self.groupBox_settings)
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.horizontalLayout.addWidget(self.lineEdit_dir)
        self.pushButton_browse = QtGui.QPushButton(self.groupBox_settings)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout.addWidget(self.pushButton_browse)
        self.pushButton_scan = QtGui.QPushButton(self.groupBox_settings)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.horizontalLayout.addWidget(self.pushButton_scan)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_settings)
        self.groupBox_results = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_results.setObjectName("groupBox_results")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_results)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_dup = QtGui.QTreeWidget(self.groupBox_results)
        self.treeWidget_dup.setRootIsDecorated(False)
        self.treeWidget_dup.setItemsExpandable(False)
        self.treeWidget_dup.setColumnCount(5)
        self.treeWidget_dup.setObjectName("treeWidget_dup")
        self.treeWidget_dup.header().setCascadingSectionResizes(True)
        self.treeWidget_dup.header().setDefaultSectionSize(150)
        self.treeWidget_dup.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.treeWidget_dup)
        self.tabWidget = QtGui.QTabWidget(self.groupBox_results)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_all = QtGui.QListWidget(self.tab)
        self.listWidget_all.setObjectName("listWidget_all")
        self.verticalLayout_3.addWidget(self.listWidget_all)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.groupBox_results)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        dupfind.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(dupfind)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        dupfind.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(dupfind)
        self.statusbar.setObjectName("statusbar")
        dupfind.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(dupfind)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(dupfind)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(dupfind)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), dupfind.close)
        QtCore.QMetaObject.connectSlotsByName(dupfind)

    def retranslateUi(self, dupfind):
        dupfind.setWindowTitle(QtGui.QApplication.translate("dupfind", "DupFind", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_settings.setTitle(QtGui.QApplication.translate("dupfind", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pick_Dir.setText(QtGui.QApplication.translate("dupfind", "Directory to scan:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browse.setText(QtGui.QApplication.translate("dupfind", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_scan.setText(QtGui.QApplication.translate("dupfind", "Start Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_results.setTitle(QtGui.QApplication.translate("dupfind", "Click an item to get a list of found duplicates", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_dup.headerItem().setText(0, QtGui.QApplication.translate("dupfind", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_dup.headerItem().setText(1, QtGui.QApplication.translate("dupfind", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_dup.headerItem().setText(2, QtGui.QApplication.translate("dupfind", "Modified", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_dup.headerItem().setText(3, QtGui.QApplication.translate("dupfind", "Created", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_dup.headerItem().setText(4, QtGui.QApplication.translate("dupfind", "Accessed", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("dupfind", "Duplicates", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("dupfind", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("dupfind", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("dupfind", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("dupfind", "about", None, QtGui.QApplication.UnicodeUTF8))

